# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 354f3dc68d213deddb16b8318170017648579e64787c85c4cc9537b4c8c62e2d26b35398dea80a9249ecaf5e36213acea3087e33f9ba50043027571722fa62b4

test:
  secret_key_base: 86df15c8f15330613c67a7592577d7d0cab4f0a8be41378c101bf70c5084e4f26ff72fb91b4174dfb14e7633ab10420eccd9d71e742c8a479716c8668a2263ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
